// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trade.Persistance.Context;

#nullable disable

namespace Trade.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240905012505_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trade.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("Quanty")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransactTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ed08877-0edb-45ed-8e7a-f43e7d5801a7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 522.99m,
                            Quanty = 1000,
                            Side = 0,
                            Symbol = "META",
                            TransactTime = new DateTime(2024, 9, 4, 20, 25, 4, 768, DateTimeKind.Local).AddTicks(7368),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b97496be-9aec-4a06-847b-1529a410b1ca"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 424.30m,
                            Quanty = 300,
                            Side = 0,
                            Symbol = "MICROSOFT",
                            TransactTime = new DateTime(2024, 9, 4, 20, 25, 4, 768, DateTimeKind.Local).AddTicks(7393),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("99b41f2e-cfb2-4457-abff-e6315e1d0763"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0m,
                            Quanty = 400,
                            Side = 1,
                            Symbol = "AMAZON",
                            TransactTime = new DateTime(2024, 9, 4, 20, 25, 4, 768, DateTimeKind.Local).AddTicks(7395),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f29a98c5-41b0-42d2-96ef-d0d6ee2fe418"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0m,
                            Quanty = 800,
                            Side = 1,
                            Symbol = "TESLA",
                            TransactTime = new DateTime(2024, 9, 4, 20, 25, 4, 768, DateTimeKind.Local).AddTicks(7397),
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
