// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trade.Persistance.Context;

#nullable disable

namespace Trade.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trade.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("Quanty")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TransactTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef5f0f31-4a74-49fc-8d1d-1b0ced81aab9"),
                            Created = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1641),
                            CreatedBy = "System",
                            Currency = "USD",
                            Price = 522.99m,
                            Quanty = 1000,
                            Side = 0,
                            Symbol = "META",
                            Text = "",
                            TransactTime = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1629),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b896c9eb-1608-4a7e-976c-a03aff28d0f9"),
                            Created = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1666),
                            CreatedBy = "System",
                            Currency = "USD",
                            Price = 424.30m,
                            Quanty = 300,
                            Side = 0,
                            Symbol = "MICROSOFT",
                            Text = "",
                            TransactTime = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1665),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d613c5b5-71c4-48f5-bea7-bc8956993740"),
                            Created = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1669),
                            CreatedBy = "System",
                            Currency = "USD",
                            Price = 0m,
                            Quanty = 400,
                            Side = 1,
                            Symbol = "AMAZON",
                            Text = "",
                            TransactTime = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1669),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5df19077-8657-4e10-98ea-a0519587f6ea"),
                            Created = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1671),
                            CreatedBy = "System",
                            Currency = "USD",
                            Price = 0m,
                            Quanty = 800,
                            Side = 1,
                            Symbol = "TESLA",
                            Text = "",
                            TransactTime = new DateTime(2024, 9, 4, 20, 44, 59, 50, DateTimeKind.Local).AddTicks(1671),
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
